// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package outbox

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOutboxScenario(ctx context.Context, arg CreateOutboxScenarioParams) (OutboxScenario, error)
	GetPendingOutboxScenarios(ctx context.Context, limit int32) ([]OutboxScenario, error)
	LockOutboxScenario(ctx context.Context, arg LockOutboxScenarioParams) error
	LockOutboxScenariosBatch(ctx context.Context, dollar_1 []pgtype.UUID) error
	MarkOutboxScenariosAsSentBatch(ctx context.Context, dollar_1 []pgtype.UUID) error
	UpdateOutboxScenarioState(ctx context.Context, arg UpdateOutboxScenarioStateParams) error
}

var _ Querier = (*Queries)(nil)
