// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	CreateOutboxScenario(ctx context.Context, arg CreateOutboxScenarioParams) (OutboxScenario, error)
	CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error)
	UpdateOutboxScenarioState(ctx context.Context, arg UpdateOutboxScenarioStateParams) error
	UpdateScenarioPredictByUUID(ctx context.Context, arg UpdateScenarioPredictByUUIDParams) error
	UpdateScenarioStatusByUUID(ctx context.Context, arg UpdateScenarioStatusByUUIDParams) error
}

var _ Querier = (*Queries)(nil)
