// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxScenario = `-- name: CreateOutboxScenario :one
INSERT INTO outbox_scenario (
    outbox_uuid,
    scenario_uuid,
    payload
) VALUES (
    $1, $2, $3
) RETURNING outbox_uuid, scenario_uuid, payload, state, created_at, updated_at
`

type CreateOutboxScenarioParams struct {
	OutboxUuid   pgtype.UUID `json:"outbox_uuid"`
	ScenarioUuid pgtype.UUID `json:"scenario_uuid"`
	Payload      []byte      `json:"payload"`
}

func (q *Queries) CreateOutboxScenario(ctx context.Context, arg CreateOutboxScenarioParams) (OutboxScenario, error) {
	row := q.db.QueryRow(ctx, createOutboxScenario, arg.OutboxUuid, arg.ScenarioUuid, arg.Payload)
	var i OutboxScenario
	err := row.Scan(
		&i.OutboxUuid,
		&i.ScenarioUuid,
		&i.Payload,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScenario = `-- name: CreateScenario :one
INSERT INTO scenario (
    uuid,
    camera_id
) VALUES (
    $1, $2
) RETURNING uuid, camera_id, predict_id, status, created_at, updated_at
`

type CreateScenarioParams struct {
	Uuid     pgtype.UUID `json:"uuid"`
	CameraID int32       `json:"camera_id"`
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, createScenario, arg.Uuid, arg.CameraID)
	var i Scenario
	err := row.Scan(
		&i.Uuid,
		&i.CameraID,
		&i.PredictID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOutboxScenarioState = `-- name: UpdateOutboxScenarioState :exec
UPDATE outbox_scenario
SET state = $2,
    updated_at = NOW()
WHERE scenario_uuid = $1
`

type UpdateOutboxScenarioStateParams struct {
	ScenarioUuid pgtype.UUID `json:"scenario_uuid"`
	State        *string     `json:"state"`
}

func (q *Queries) UpdateOutboxScenarioState(ctx context.Context, arg UpdateOutboxScenarioStateParams) error {
	_, err := q.db.Exec(ctx, updateOutboxScenarioState, arg.ScenarioUuid, arg.State)
	return err
}

const updateScenarioPredictByUUID = `-- name: UpdateScenarioPredictByUUID :exec
UPDATE scenario
SET predict_id = $2,
    updated_at = NOW()
WHERE uuid = $1
`

type UpdateScenarioPredictByUUIDParams struct {
	Uuid      pgtype.UUID `json:"uuid"`
	PredictID *int32      `json:"predict_id"`
}

func (q *Queries) UpdateScenarioPredictByUUID(ctx context.Context, arg UpdateScenarioPredictByUUIDParams) error {
	_, err := q.db.Exec(ctx, updateScenarioPredictByUUID, arg.Uuid, arg.PredictID)
	return err
}

const updateScenarioStatusByUUID = `-- name: UpdateScenarioStatusByUUID :exec
UPDATE scenario
SET status = $2,
    updated_at = NOW()
WHERE uuid = $1
`

type UpdateScenarioStatusByUUIDParams struct {
	Uuid   pgtype.UUID `json:"uuid"`
	Status *string     `json:"status"`
}

func (q *Queries) UpdateScenarioStatusByUUID(ctx context.Context, arg UpdateScenarioStatusByUUIDParams) error {
	_, err := q.db.Exec(ctx, updateScenarioStatusByUUID, arg.Uuid, arg.Status)
	return err
}
