// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package worker

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Inbox pattern table for idempotent message processing in SAGA (start scenario events)
type InboxStartScenario struct {
	// Unique identifier from the outbox message (serves as primary key for idempotency)
	OutboxUuid pgtype.UUID `json:"outbox_uuid"`
	// ID of the camera associated with the scenario
	CameraID int32 `json:"camera_id"`
	// UUID of the scenario being started
	ScenarioUuid pgtype.UUID `json:"scenario_uuid"`
	// URL associated with the scenario
	Url string `json:"url"`
	// Processing status: received, in_process, processed
	Status string `json:"status"`
	// Timestamp when the message was first received
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// Timestamp when the message status was last updated
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Node struct {
	ID      int32  `json:"id"`
	Address string `json:"address"`
	State   string `json:"state"`
}

type NodeWorker struct {
	ID       int32 `json:"id"`
	NodeID   int32 `json:"node_id"`
	WorkerID int32 `json:"worker_id"`
}

type Worker struct {
	ID           int32            `json:"id"`
	CameraID     int32            `json:"camera_id"`
	Url          string           `json:"url"`
	ScenarioUuid pgtype.UUID      `json:"scenario_uuid"`
	State        string           `json:"state"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
