// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package worker

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error)
	DeleteWorker(ctx context.Context, id int32) error
	GetWorkerByID(ctx context.Context, id int32) (Worker, error)
	GetWorkersByScenarioUUID(ctx context.Context, scenarioUuid pgtype.UUID) ([]Worker, error)
	UpdateWorkerState(ctx context.Context, arg UpdateWorkerStateParams) (Worker, error)
}

var _ Querier = (*Queries)(nil)
