// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker_queries.sql

package worker

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO worker (
    camera_id,
    url,
    scenario_uuid,
    state
) VALUES (
    $1, $2, $3, $4
) RETURNING id, camera_id, url, scenario_uuid, state, created_at, updated_at
`

type CreateWorkerParams struct {
	CameraID     int32       `json:"camera_id"`
	Url          string      `json:"url"`
	ScenarioUuid pgtype.UUID `json:"scenario_uuid"`
	State        string      `json:"state"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.CameraID,
		arg.Url,
		arg.ScenarioUuid,
		arg.State,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Url,
		&i.ScenarioUuid,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM worker WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWorker, id)
	return err
}

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT id, camera_id, url, scenario_uuid, state, created_at, updated_at FROM worker WHERE id = $1
`

func (q *Queries) GetWorkerByID(ctx context.Context, id int32) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Url,
		&i.ScenarioUuid,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkersByScenarioUUID = `-- name: GetWorkersByScenarioUUID :many
SELECT id, camera_id, url, scenario_uuid, state, created_at, updated_at FROM worker WHERE scenario_uuid = $1
`

func (q *Queries) GetWorkersByScenarioUUID(ctx context.Context, scenarioUuid pgtype.UUID) ([]Worker, error) {
	rows, err := q.db.Query(ctx, getWorkersByScenarioUUID, scenarioUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Url,
			&i.ScenarioUuid,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkerState = `-- name: UpdateWorkerState :one
UPDATE worker SET state = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, camera_id, url, scenario_uuid, state, created_at, updated_at
`

type UpdateWorkerStateParams struct {
	ID    int32  `json:"id"`
	State string `json:"state"`
}

func (q *Queries) UpdateWorkerState(ctx context.Context, arg UpdateWorkerStateParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorkerState, arg.ID, arg.State)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Url,
		&i.ScenarioUuid,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
