// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker_queries.sql

package worker

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNodeWorker = `-- name: CreateNodeWorker :one
INSERT INTO node_worker (
    node_id,
    worker_id
) VALUES (
    $1, $2
) RETURNING id, node_id, worker_id, assigned_at
`

type CreateNodeWorkerParams struct {
	NodeID   string `json:"node_id"`
	WorkerID int32  `json:"worker_id"`
}

func (q *Queries) CreateNodeWorker(ctx context.Context, arg CreateNodeWorkerParams) (NodeWorker, error) {
	row := q.db.QueryRow(ctx, createNodeWorker, arg.NodeID, arg.WorkerID)
	var i NodeWorker
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.WorkerID,
		&i.AssignedAt,
	)
	return i, err
}

const createWorker = `-- name: CreateWorker :one
INSERT INTO worker (
    camera_id,
    scenario_uuid,
    url,
    status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, camera_id, scenario_uuid, url, status, created_at, updated_at
`

type CreateWorkerParams struct {
	CameraID     int32       `json:"camera_id"`
	ScenarioUuid pgtype.UUID `json:"scenario_uuid"`
	Url          string      `json:"url"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.CameraID,
		arg.ScenarioUuid,
		arg.Url,
		arg.Status,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.ScenarioUuid,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNodeWorkerByWorkerID = `-- name: DeleteNodeWorkerByWorkerID :exec
DELETE FROM node_worker WHERE worker_id = $1
`

func (q *Queries) DeleteNodeWorkerByWorkerID(ctx context.Context, workerID int32) error {
	_, err := q.db.Exec(ctx, deleteNodeWorkerByWorkerID, workerID)
	return err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM worker WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWorker, id)
	return err
}

const getLeastLoadedNodes = `-- name: GetLeastLoadedNodes :many
SELECT n.id as node_id, n.addr, COUNT(nw.worker_id) as worker_count
FROM node n
LEFT JOIN node_worker nw ON n.id = nw.node_id
GROUP BY n.id, n.addr
ORDER BY worker_count ASC
LIMIT $1
`

type GetLeastLoadedNodesRow struct {
	NodeID      string `json:"node_id"`
	Addr        string `json:"addr"`
	WorkerCount int64  `json:"worker_count"`
}

func (q *Queries) GetLeastLoadedNodes(ctx context.Context, limit int32) ([]GetLeastLoadedNodesRow, error) {
	rows, err := q.db.Query(ctx, getLeastLoadedNodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeastLoadedNodesRow{}
	for rows.Next() {
		var i GetLeastLoadedNodesRow
		if err := rows.Scan(&i.NodeID, &i.Addr, &i.WorkerCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOldestWorkersByStatus = `-- name: GetOldestWorkersByStatus :many
SELECT id, camera_id, scenario_uuid, url, status, created_at, updated_at FROM worker WHERE status = $1 ORDER BY created_at ASC LIMIT $2
`

type GetOldestWorkersByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetOldestWorkersByStatus(ctx context.Context, arg GetOldestWorkersByStatusParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, getOldestWorkersByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.ScenarioUuid,
			&i.Url,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkerByCameraID = `-- name: GetWorkerByCameraID :one
SELECT id, camera_id, scenario_uuid, url, status, created_at, updated_at FROM worker WHERE camera_id = $1
`

func (q *Queries) GetWorkerByCameraID(ctx context.Context, cameraID int32) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByCameraID, cameraID)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.ScenarioUuid,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkerStatus = `-- name: UpdateWorkerStatus :one
UPDATE worker SET status = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2 RETURNING id, camera_id, scenario_uuid, url, status, created_at, updated_at
`

type UpdateWorkerStatusParams struct {
	Status string `json:"status"`
	ID     int32  `json:"id"`
}

func (q *Queries) UpdateWorkerStatus(ctx context.Context, arg UpdateWorkerStatusParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorkerStatus, arg.Status, arg.ID)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.ScenarioUuid,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
