// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox_start_scenario_queries.sql

package inbox_start_scenario

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInboxStartScenario = `-- name: CreateInboxStartScenario :one
INSERT INTO inbox_start_scenario (
    outbox_uuid,
    camera_id,
    scenario_uuid,
    url
) VALUES (
    $1, $2, $3, $4
) RETURNING outbox_uuid, camera_id, scenario_uuid, url, status, created_at, updated_at
`

type CreateInboxStartScenarioParams struct {
	OutboxUuid   pgtype.UUID `json:"outbox_uuid"`
	CameraID     int32       `json:"camera_id"`
	ScenarioUuid pgtype.UUID `json:"scenario_uuid"`
	Url          string      `json:"url"`
}

func (q *Queries) CreateInboxStartScenario(ctx context.Context, arg CreateInboxStartScenarioParams) (InboxStartScenario, error) {
	row := q.db.QueryRow(ctx, createInboxStartScenario,
		arg.OutboxUuid,
		arg.CameraID,
		arg.ScenarioUuid,
		arg.Url,
	)
	var i InboxStartScenario
	err := row.Scan(
		&i.OutboxUuid,
		&i.CameraID,
		&i.ScenarioUuid,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
