// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package inbox_start_scenario

import (
	"context"
)

type Querier interface {
	CreateInboxStartScenario(ctx context.Context, arg CreateInboxStartScenarioParams) (InboxStartScenario, error)
}

var _ Querier = (*Queries)(nil)
