// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package scenario

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Outbox pattern table for reliable message publishing in SAGA
type OutboxScenario struct {
	OutboxUuid pgtype.UUID `json:"outbox_uuid"`
	// UUID of the associated scenario from scenario table
	ScenarioUuid pgtype.UUID `json:"scenario_uuid"`
	// JSON data of the message payload
	Payload []byte `json:"payload"`
	// State of the message (pending, sent, failed)
	State *string `json:"state"`
	// Timestamp when the message was created
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// Timestamp when the message was last updated
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	// Timestamp until which the outbox message is locked from being processed
	LockedUntil pgtype.Timestamp `json:"locked_until"`
}

// Scenario table for storing scenario state and camera prediction
type Scenario struct {
	// Unique identifier for the scenario (UUID format)
	Uuid pgtype.UUID `json:"uuid"`
	// ID of the camera being used in the scenario
	CameraID int32 `json:"camera_id"`
	// ID of the predicted person
	PredictID *int32 `json:"predict_id"`
	// Status of the scenario (init_startup, in_startup_processing, active, init_shutdown, in_shutdown_processing, inactive)
	Status *string `json:"status"`
	// Timestamp when the scenario was created
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// Timestamp when the scenario was last updated
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
