// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenario_queries.sql

package scenario

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScenario = `-- name: CreateScenario :one
INSERT INTO scenario (
    uuid,
    camera_id
) VALUES (
    $1, $2
) RETURNING uuid, camera_id, predict_id, status, created_at, updated_at
`

type CreateScenarioParams struct {
	Uuid     pgtype.UUID `json:"uuid"`
	CameraID int32       `json:"camera_id"`
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, createScenario, arg.Uuid, arg.CameraID)
	var i Scenario
	err := row.Scan(
		&i.Uuid,
		&i.CameraID,
		&i.PredictID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScenarioPredictByUUID = `-- name: UpdateScenarioPredictByUUID :exec
UPDATE scenario
SET predict_id = $2,
    updated_at = NOW()
WHERE uuid = $1
`

type UpdateScenarioPredictByUUIDParams struct {
	Uuid      pgtype.UUID `json:"uuid"`
	PredictID *int32      `json:"predict_id"`
}

func (q *Queries) UpdateScenarioPredictByUUID(ctx context.Context, arg UpdateScenarioPredictByUUIDParams) error {
	_, err := q.db.Exec(ctx, updateScenarioPredictByUUID, arg.Uuid, arg.PredictID)
	return err
}

const updateScenarioStatusBatch = `-- name: UpdateScenarioStatusBatch :exec
UPDATE scenario
SET status = $2,
    updated_at = NOW()
WHERE uuid = ANY($1::uuid[])
`

type UpdateScenarioStatusBatchParams struct {
	Column1 []pgtype.UUID `json:"column_1"`
	Status  *string       `json:"status"`
}

func (q *Queries) UpdateScenarioStatusBatch(ctx context.Context, arg UpdateScenarioStatusBatchParams) error {
	_, err := q.db.Exec(ctx, updateScenarioStatusBatch, arg.Column1, arg.Status)
	return err
}

const updateScenarioStatusByUUID = `-- name: UpdateScenarioStatusByUUID :exec
UPDATE scenario
SET status = $2,
    updated_at = NOW()
WHERE uuid = $1
`

type UpdateScenarioStatusByUUIDParams struct {
	Uuid   pgtype.UUID `json:"uuid"`
	Status *string     `json:"status"`
}

func (q *Queries) UpdateScenarioStatusByUUID(ctx context.Context, arg UpdateScenarioStatusByUUIDParams) error {
	_, err := q.db.Exec(ctx, updateScenarioStatusByUUID, arg.Uuid, arg.Status)
	return err
}
