// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: inference/v1/inference.proto

package inferencepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос с изображением
type DetectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"` // Изображение в байтах (JPEG, PNG и т.д.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *DetectRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

// Прямоугольник с координатами объекта
type Rectangle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X0            float32                `protobuf:"fixed32,1,opt,name=x0,proto3" json:"x0,omitempty"` // Левая верхняя точка X
	Y0            float32                `protobuf:"fixed32,2,opt,name=y0,proto3" json:"y0,omitempty"` // Левая верхняя точка Y
	X1            float32                `protobuf:"fixed32,3,opt,name=x1,proto3" json:"x1,omitempty"` // Правая нижняя точка X
	Y1            float32                `protobuf:"fixed32,4,opt,name=y1,proto3" json:"y1,omitempty"` // Правая нижняя точка Y
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	mi := &file_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *Rectangle) GetX0() float32 {
	if x != nil {
		return x.X0
	}
	return 0
}

func (x *Rectangle) GetY0() float32 {
	if x != nil {
		return x.Y0
	}
	return 0
}

func (x *Rectangle) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Rectangle) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

// Один обнаруженный объект
type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"` // Название класса объекта
	Rectangle     *Rectangle             `protobuf:"bytes,2,opt,name=rectangle,proto3" json:"rectangle,omitempty"`                  // Координаты bounding box
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *Detection) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Detection) GetRectangle() *Rectangle {
	if x != nil {
		return x.Rectangle
	}
	return nil
}

// Ответ с результатами детекции
type DetectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detections    []*Detection           `protobuf:"bytes,1,rep,name=detections,proto3" json:"detections,omitempty"` // Список обнаруженных объектов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	mi := &file_inference_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *DetectResponse) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

var File_inference_v1_inference_proto protoreflect.FileDescriptor

const file_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\x1cinference/v1/inference.proto\x12\finference.v1\"%\n" +
	"\rDetectRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"K\n" +
	"\tRectangle\x12\x0e\n" +
	"\x02x0\x18\x01 \x01(\x02R\x02x0\x12\x0e\n" +
	"\x02y0\x18\x02 \x01(\x02R\x02y0\x12\x0e\n" +
	"\x02x1\x18\x03 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x04 \x01(\x02R\x02y1\"a\n" +
	"\tDetection\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\x125\n" +
	"\trectangle\x18\x02 \x01(\v2\x17.inference.v1.RectangleR\trectangle\"I\n" +
	"\x0eDetectResponse\x127\n" +
	"\n" +
	"detections\x18\x01 \x03(\v2\x17.inference.v1.DetectionR\n" +
	"detections2W\n" +
	"\x10InferenceService\x12C\n" +
	"\x06Detect\x12\x1b.inference.v1.DetectRequest\x1a\x1c.inference.v1.DetectResponseB.Z,runner/proto/client/inference/v1;inferencepbb\x06proto3"

var (
	file_inference_v1_inference_proto_rawDescOnce sync.Once
	file_inference_v1_inference_proto_rawDescData []byte
)

func file_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_v1_inference_proto_rawDesc), len(file_inference_v1_inference_proto_rawDesc)))
	})
	return file_inference_v1_inference_proto_rawDescData
}

var file_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inference_v1_inference_proto_goTypes = []any{
	(*DetectRequest)(nil),  // 0: inference.v1.DetectRequest
	(*Rectangle)(nil),      // 1: inference.v1.Rectangle
	(*Detection)(nil),      // 2: inference.v1.Detection
	(*DetectResponse)(nil), // 3: inference.v1.DetectResponse
}
var file_inference_v1_inference_proto_depIdxs = []int32{
	1, // 0: inference.v1.Detection.rectangle:type_name -> inference.v1.Rectangle
	2, // 1: inference.v1.DetectResponse.detections:type_name -> inference.v1.Detection
	0, // 2: inference.v1.InferenceService.Detect:input_type -> inference.v1.DetectRequest
	3, // 3: inference.v1.InferenceService.Detect:output_type -> inference.v1.DetectResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inference_v1_inference_proto_init() }
func file_inference_v1_inference_proto_init() {
	if File_inference_v1_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_v1_inference_proto_rawDesc), len(file_inference_v1_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_inference_v1_inference_proto_depIdxs,
		MessageInfos:      file_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_inference_v1_inference_proto = out.File
	file_inference_v1_inference_proto_goTypes = nil
	file_inference_v1_inference_proto_depIdxs = nil
}
