// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: error_marker_queries.sql

package error_marker

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStaleNodes = `-- name: GetStaleNodes :many
SELECT
    n.id,
    n.addr,
    n.state,
    MAX(he.updated_at)::timestamp AS last_heartbeat
FROM node n
LEFT JOIN heartbeat_events he ON he.node_id = n.id
GROUP BY n.id, n.addr, n.state, n.created_at
HAVING COALESCE(MAX(he.updated_at), n.created_at) < NOW() - make_interval(secs => $1)
`

type GetStaleNodesRow struct {
	ID            int32            `json:"id"`
	Addr          string           `json:"addr"`
	State         string           `json:"state"`
	LastHeartbeat pgtype.Timestamp `json:"last_heartbeat"`
}

func (q *Queries) GetStaleNodes(ctx context.Context, secs float64) ([]GetStaleNodesRow, error) {
	rows, err := q.db.Query(ctx, getStaleNodes, secs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleNodesRow{}
	for rows.Next() {
		var i GetStaleNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Addr,
			&i.State,
			&i.LastHeartbeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleWorkers = `-- name: GetStaleWorkers :many
SELECT
    w.id,
    w.camera_id,
    w.status,
    he.updated_at AS last_heartbeat
FROM worker w
LEFT JOIN heartbeat_events he ON he.camera_id = w.camera_id::text
WHERE COALESCE(he.updated_at, w.created_at) < NOW() - make_interval(secs => $1)
  AND w.status <> 'error'
`

type GetStaleWorkersRow struct {
	ID            int32            `json:"id"`
	CameraID      int32            `json:"camera_id"`
	Status        string           `json:"status"`
	LastHeartbeat pgtype.Timestamp `json:"last_heartbeat"`
}

func (q *Queries) GetStaleWorkers(ctx context.Context, secs float64) ([]GetStaleWorkersRow, error) {
	rows, err := q.db.Query(ctx, getStaleWorkers, secs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleWorkersRow{}
	for rows.Next() {
		var i GetStaleWorkersRow
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Status,
			&i.LastHeartbeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkersWithoutHeartbeat = `-- name: GetWorkersWithoutHeartbeat :many
SELECT
    w.id,
    w.camera_id
FROM worker w
LEFT JOIN heartbeat_events he ON he.camera_id = w.camera_id::text
WHERE he.camera_id IS NULL
`

type GetWorkersWithoutHeartbeatRow struct {
	ID       int32 `json:"id"`
	CameraID int32 `json:"camera_id"`
}

func (q *Queries) GetWorkersWithoutHeartbeat(ctx context.Context) ([]GetWorkersWithoutHeartbeatRow, error) {
	rows, err := q.db.Query(ctx, getWorkersWithoutHeartbeat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkersWithoutHeartbeatRow{}
	for rows.Next() {
		var i GetWorkersWithoutHeartbeatRow
		if err := rows.Scan(&i.ID, &i.CameraID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeAsError = `-- name: MarkNodeAsError :exec
UPDATE node SET state = 'error' WHERE id = $1 AND state <> 'error'
`

func (q *Queries) MarkNodeAsError(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markNodeAsError, id)
	return err
}

const markWorkerAsError = `-- name: MarkWorkerAsError :exec
UPDATE worker SET status = 'error', updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND status <> 'error'
`

func (q *Queries) MarkWorkerAsError(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markWorkerAsError, id)
	return err
}
