// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package error_marker

import (
	"context"
)

type Querier interface {
	GetStaleNodes(ctx context.Context, secs float64) ([]GetStaleNodesRow, error)
	GetStaleWorkers(ctx context.Context, secs float64) ([]GetStaleWorkersRow, error)
	GetWorkersWithoutHeartbeat(ctx context.Context) ([]GetWorkersWithoutHeartbeatRow, error)
	MarkNodeAsError(ctx context.Context, id int32) error
	MarkWorkerAsError(ctx context.Context, id int32) error
}

var _ Querier = (*Queries)(nil)
