// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes_queries.sql

package nodes

import (
	"context"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (address) VALUES ($1) RETURNING id, address, state
`

func (q *Queries) CreateNode(ctx context.Context, address string) (Node, error) {
	row := q.db.QueryRow(ctx, createNode, address)
	var i Node
	err := row.Scan(&i.ID, &i.Address, &i.State)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getAllNodes = `-- name: GetAllNodes :many
SELECT id, address, state FROM nodes
`

func (q *Queries) GetAllNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, getAllNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(&i.ID, &i.Address, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, address, state FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id int32) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(&i.ID, &i.Address, &i.State)
	return i, err
}
