// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package nodes

import (
	"context"
)

type Querier interface {
	CreateNode(ctx context.Context, address string) (Node, error)
	DeleteNode(ctx context.Context, id int32) error
	GetAllNodes(ctx context.Context) ([]Node, error)
	GetNodeByID(ctx context.Context, id int32) (Node, error)
}

var _ Querier = (*Queries)(nil)
