// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package heartbeat

import (
	"context"
)

type Querier interface {
	UpsertHeartbeat(ctx context.Context, arg UpsertHeartbeatParams) error
}

var _ Querier = (*Queries)(nil)
