// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_worker_queries.sql

package node_worker

import (
	"context"
)

const createNodeWorker = `-- name: CreateNodeWorker :one
INSERT INTO node_worker (node_id, worker_id) VALUES ($1, $2) RETURNING id, node_id, worker_id
`

type CreateNodeWorkerParams struct {
	NodeID   int32 `json:"node_id"`
	WorkerID int32 `json:"worker_id"`
}

func (q *Queries) CreateNodeWorker(ctx context.Context, arg CreateNodeWorkerParams) (NodeWorker, error) {
	row := q.db.QueryRow(ctx, createNodeWorker, arg.NodeID, arg.WorkerID)
	var i NodeWorker
	err := row.Scan(&i.ID, &i.NodeID, &i.WorkerID)
	return i, err
}

const deleteNodeWorker = `-- name: DeleteNodeWorker :exec
DELETE FROM node_worker WHERE node_id = $1 AND worker_id = $2
`

type DeleteNodeWorkerParams struct {
	NodeID   int32 `json:"node_id"`
	WorkerID int32 `json:"worker_id"`
}

func (q *Queries) DeleteNodeWorker(ctx context.Context, arg DeleteNodeWorkerParams) error {
	_, err := q.db.Exec(ctx, deleteNodeWorker, arg.NodeID, arg.WorkerID)
	return err
}

const getNodeByWorkerID = `-- name: GetNodeByWorkerID :one
SELECT n.id, n.address, n.state FROM nodes n
JOIN node_worker nw ON n.id = nw.node_id
WHERE nw.worker_id = $1
`

func (q *Queries) GetNodeByWorkerID(ctx context.Context, workerID int32) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByWorkerID, workerID)
	var i Node
	err := row.Scan(&i.ID, &i.Address, &i.State)
	return i, err
}

const getWorkersByNodeID = `-- name: GetWorkersByNodeID :many
SELECT w.id, w.camera_id, w.url, w.scenario_uuid, w.state, w.created_at, w.updated_at FROM worker w
JOIN node_worker nw ON w.id = nw.worker_id
WHERE nw.node_id = $1
`

func (q *Queries) GetWorkersByNodeID(ctx context.Context, nodeID int32) ([]Worker, error) {
	rows, err := q.db.Query(ctx, getWorkersByNodeID, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Url,
			&i.ScenarioUuid,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
