// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package node_worker

import (
	"context"
)

type Querier interface {
	CreateNodeWorker(ctx context.Context, arg CreateNodeWorkerParams) (NodeWorker, error)
	DeleteNodeWorker(ctx context.Context, arg DeleteNodeWorkerParams) error
	GetNodeByWorkerID(ctx context.Context, workerID int32) (Node, error)
	GetWorkersByNodeID(ctx context.Context, nodeID int32) ([]Worker, error)
}

var _ Querier = (*Queries)(nil)
